// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kufkpsoygixjaotmadvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1Zmtwc295Z2l4amFvdG1hZHZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5MzY1MjIsImV4cCI6MjA3NzUxMjUyMn0.gvnJSZ4qYRE7ndKIljoc0xWL5RpP1Im7JIQLASDAsCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});